sudo: required
services:
  - docker
before_install:
  - docker build -t sumannakkala/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true sumannakkala/docker-react npm run test -- --coverage
 